name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./TechXpress/TechXpress.Web.csproj

    - name: Build project
      run: dotnet build ./TechXpress/TechXpress.Web.csproj --configuration Release

    - name: Publish project
      run: dotnet publish ./TechXpress/TechXpress.Web.csproj -c Release -o published

    - name: Push to GitHub (published folder)
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add published -f
        git commit -m "Add published files"
        git push origin main
